pages:
  image: python:3.8
  stage: deploy
  script:
    - pip install -r docs/requirements.txt
    - python -m mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - validation
