service: serverless-example

custom:
  stage: ${opt:stage, 'dev'}

functions:
  hello_world:
    timeout: 10
    handler: api/hello.lambda_handler
    events:
      - http:
          path: /hello_world
          method: get
          cors: true
  users:
    timeout: 10
    handler: api/users.lambda_handler
    events:
      - http:
          path: /users
          method: ANY
          cors: true

provider:
  name: aws
  region: us-east-1
  runtime: python3.8
  stage: ${self:custom.stage}
  environment:

package:
  exclude:
    - node_modules/**
    - .metals/**
    - "**/__pycache__/**"
    - serverless.yml
